[master]
master ansible_host=35.180.69.133 ansible_user=ubuntu ansible_ssh_private_key_file=/home/hp/.ssh/devops-key

[worker]
worker ansible_host=13.39.47.85 ansible_user=ubuntu ansible_ssh_private_key_file=/home/hp/.ssh/devops-key

[k8s_cluster:children]
master
worker